/* ccideinline.c: Generate inline code or skeleton program */

#include "ccide.h"
#include <stdio.h>
#include <string.h>
#include "ccidemain.h"


#define J(L) printf("%s %c",L,'\n');

char *slang="";

void GenInLineCode(char *s) {

	if( noinline ) 
		return;

	noinline=1;

	if(m4out) {
		printf("%s_INLINECODE\()\n", pPrefix);
		if(changequote) {
			printf("%sGENERATED_CODE: %s\n",pComment,pEcomment);
			printf("CCIDE_COMMENT\() Substitution strings are: %s and %s\n", 
				svar1, svar2); 
			// printf("CCIDE_COMMENT\() changequote\(%s, %s)\n", 
			// 	qt1, qt2);
			printf("%sEND_GENERATED_CODE: %s\n",pComment,pEcomment);
		}
		return;
	}

printf("%sGENERATED_CODE: %s\n",pComment,pEcomment);
printf("#ifndef __%s_INLINE_C\n", pPrefix);
printf("#define __%s_INLINE_C\n\n/*", pPrefix);

printf("ccide-%s-%s\n", VERSION, RELEASE);  
J("Copyright (C) 2002-2010 Thomas W. Young, e-mail:  ccide@twyoung.com")
J("This code (generated by ccide) is licensed under the GNU Library") 
J("General Public License ")
J("As such, it may be freely used, even link-editted with proprietary code")
J("*/")
printf ("static int %s_group=1;", pPrefixLc);
J("")
J("#ifndef UINT_MAX")
J("#include \"limits.h\"")
J("#endif ")
J("")
J("		/* Return rule number */")
printf("static int %sFindRule\(\n", pPrefix);
printf("	int nbrrules,  unsigned long ccide_table, unsigned long yes[], unsigned long no[])");
J("{")
J("        int r=0;")
J("        unsigned long nstate;")
J("")
J("        nstate = UINT_MAX ^ ccide_table;")
J("")
J("        while \(")
J("		\( \(yes[r] & nstate) || \(no[r]  & ccide_table) )")
J("		 && \( ++r < nbrrules ) ")
J("	) {};")
J("")
J("        return r;")
J("}")
J("")
printf("static int %sFindRuleYes\(             /* Return rule number */\n", pPrefix);
J("	int nbrrules, unsigned long ccide_table, unsigned long yes[])")
J("{")
J("        int r=0;")
printf("        unsigned long nstate;\n");
J("")
J("        nstate = UINT_MAX ^ ccide_table;")
J("        while \( \(yes[r] & nstate) && \( ++r < nbrrules ) ) {};")
J("        return r;")
J("}")
printf("#endif /* End ifndef  __%s_INLINE_C  */\n", pPrefix);
printf("%sEND_GENERATED_CODE: %s\n",pComment,pEcomment);

}   /* End of GenInLineCode() */


int GenSkeleton(char *s) {
	int i,j,skelsize=4,size,RC=0;
	char *sep=" ";
	int c[32][CCIDE_NRULE];
	int logsize=1;  /* log(s) skelsize. */
	int l=2;

	if(s != NULL) {
		size=atoi(s);
		if(size>0) {
			skelsize = size;
		}	
		RC = 1;
	}

	assert(MAX_SKELSIZE < CCIDE_NRULE);

	if(skelsize>MAX_SKELSIZE) {
		fprintf(stderr,
			"%i exeeds maximum skeleton size:%i.  Resetting.\n",
				skelsize, MAX_SKELSIZE);
		skelsize=MAX_SKELSIZE;
	}

#ifdef JUNK
        if(skelsize>100){
              // bar = strdup("____");
              // sep = strdup("   ");
        } else if(skelsize>10) {
              // bar = strdup("___");
              // sep = strdup("  ");
	}
#endif

printf("%s Skeleton Program Generated by ccide-%s.%s %s %s\n",
	pComment, VERSION, RELEASE, GetTimeStamp(), pEcomment);  

J("")
J("/* Copyright (C) 2002-2010 Thomas W. Young, e-mail:  ccide@twyoung.com    */")
J("/* This program is free software; you can redistribute it and/or modify   */")
J("/* it under the terms of the GNU General Public License as published by   */")
J("/* the Free Software Foundation.                                          */")
J("/*                                                                        */")
J("/* This program is distributed in the hope that it will be useful,        */")
J("/* but WITHOUT ANY WARRANTY; without even the implied warranty of         */")
J("/* MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the          */")
J("/* GNU General Public License for more details.                           */")
J("/*                                                                        */")
J("/* You should have received a copy of the GNU General Public License      */")
J("/* along with this program; if not, write to the Free Software            */")
J("/* Foundation, Inc., 675 Mass Ave, Cambridge, MA 02139, USA.              */")
J("/* ------------------------------------------ end of legal stuff -------- */")
J(" ")
J("#include <stdlib.h>")
J("#include <stdio.h>")
J("#include <assert.h>")
printf("#ifdef %s_LIB\n", pPrefix);
printf("#include <%s.h>\n",pPrefixLc);
J("#else")
printf("%s %s_INLINE_CODE:%s\n", pComment, pPrefix, pEcomment);
printf("#endif %s End #ifdef %s_LIB %s", pComment, pPrefix, pEcomment);
J("\nstatic void A(int n) {")

printf("\tprintf\((const char*)\"%s\\n\",n);\n","%i");

J("}\n")

J("int main(int argc, char **argv) {")

i = skelsize;
while( (1<<logsize) < i) logsize++; 

printf("\tint C[%i]={1",logsize);
for(i=1;i<logsize;i++) {
	printf(",1");
}

printf("};\n\n");

printf("\t%sDECISION_TABLE:%s\n", pComment, pEcomment);

#if GEN_GROUP
printf("\t%s %s ", pComment, pEcomment);
for(j=0;j<skelsize;j++) {
	   if( (skelsize>10) && (j<9) )
	           printf("%i  ", j);
	   else 
	           printf("%i ", j);
        }

printf("| %s_group == $$\n", pPrefixLc);
#endif

	/* c[32][skelsize] is a controller for condition entries 
	   if c[j] is on, then set X, else not
	*/

	/* Clear control */
for(i=0;i<32;i++) {
  for(j=0;j<skelsize;j++) {
	  c[i][j]=0;
  }
}

	/* Set Control */
   for(i=0;i<32;i++) {
     if(1) {
	for(j=0;j<skelsize;j++) {
		int k;
		for(k=0;k<(l/2);k++) {
			c[i][j+k]=1;
		}
		j += (l-1);
  	}
	if(l < CCIDE_NRULE)
		l += l;
     }
   }

for(i=0;(i<logsize)&&(i<CCIDE_NCOND);i++) {
	printf("\t%s  ", pComment);
	for(j=0;j<skelsize;j++) {
		if(c[i][j]) {
				printf("Y%s",sep);
		} else {
			printf("N%s",sep);
		}
	}
        printf("| C[%i] %s\n",i, pEcomment);
}


printf("\t%s  ", pComment);
#define bar "__"

for(j=1;j<skelsize;j++) {
           printf("%s", bar);		
        }

printf("__|_____ %s\n", pEcomment);

for(i=0;i<skelsize;i++) {
	printf("\t%s  ",pComment);
	for(j=0;j<skelsize;j++) {
		if(i==j) 
			printf("X%s",sep);
		else
			printf("-%s",sep);
	}
        printf("| A(%i);%s\n", i, pEcomment);
}

#ifdef GEN_NEWGROUP
printf("\t%s  ", pComment);

for(j=0;j<skelsize;j++) {
	if( (skelsize>10) && (j<10) ) 
       	   printf("%i  ", j);
	else
       	   printf("%i ", j);
}

printf("| NEWGROUP\n");
#endif

printf("\t%sEND_TABLE:%s\n", pComment, pEcomment);
J("")
J("	return 0;")
J("}") 
J("")
printf("%sEnd of Skeleton Program.%s\n", pComment, pEcomment);

	return RC;
}   /* End of GenSkeleton */

void Usage() {

J("Usage:")
J("         ccidew -s [SKELETONSIZE]")
J("       | ccidew -V")
J("       | ccidew --help")
J("       | ccidew [-a] [-b] [-c COLUMNSIZE] [-d STUBSTRING1 STUBSTRING2] [-e] [-l] ")
J("               [-L LANG] [-m4] [-n] [-p PREFIX] [-q LEFTQUOTE RIGHTQUOTE]") 
J("	          [-s SKELSIZE][-t] [-u] [-x] < STDIN > STDOUT")

        RC=1; exit(1);
}

void ShowCopyright() {

printf("    ccidew version %s-%s, Copyright (C) 2002-2010 Thomas W. Young\n",
	VERSION,RELEASE);

printf("    %s comes with ABSOLUTELY NO WARRANTY.", PACKAGE);
J("    This is free software, and you are welcome to redistribute it")
J("    under certain conditions; see file COPYING for details.")
J("    Proprietary programs containing generated CCIDE decision table")
J("    code, are covered under the terms of the GNU Library ")
J("    General Public License, meaning their distribution is not")
J("    restricted by the GPL in any manner.")

}

/* End of ccideinline.c */
