# scripts/check.sh.  Generated from check.sh.in by configure. 
EXTRA_DIST = autogen.sh src/ccide.1 ccide.spec src/ccidew ccide.spec.in ChangeLog CYGWIN-PATCHES/setup.hint.in scripts/ccide.d.in \
	src/Makefile.in  src/ccide.pod.in src/ccideconfig.h.in \
	src/ccidemain.h src/ccide.h src/gettext.h src/parse.h $(srcdir)/src/ccidelex.l \
	src/ccideinline.c  src/ccidelex.c  src/ccidemain.c  src/ccideparse.c src/ccideparse.y  src/cciderunx.c \
	tests/f1 tests/f2 tests/f3 tests/f4 tests/if2rpn.txt tests/tryit.txt tests/Makefile \
	scripts/check.sh scripts/Makefile scripts/Makefile.in scripts/ccide.d.in scripts/check.sh.in \
	po/Makefile.in.in po/Makevars po/ccide.pot po/Makevars \
	src/ccideparse.y.d
	src/ccidemain.c.d
	./tests/babble.X \
	./tests/bin2dec.X \
	./tests/bonus.X \
	./tests/calc.X \
	./tests/ccidetime.X \
	./tests/depeter.X \
	./tests/elev.X \
	./tests/ex1.X \
	./tests/fourway.X \
	./tests/hcond.X \
	./tests/huge1.X \
	./tests/huge2.X \
	./tests/hw.X \
	./tests/if2rpn.X \
	./tests/if2rpn.h  \
	./tests/quadrants3.X \
	./tests/simple.X \
	./tests/skel.X \
	./tests/threeway.X \
	./tests/tryit.X \
	./tests/babble.bbl.r \
	./tests/bin2dec.c.r \
	./tests/bonus.cpp.r \
	./tests/calc.c.r \
	./tests/ccidetime.c.err.r \
	./tests/ccidetime.c.r \
	./tests/depeter.c.r \
	./tests/elev.c.err.r \
	./tests/elev.c.r \
	./tests/errors.c.err.r \
	./tests/errors.c.r \
	./tests/ex1.bash.r \
	./tests/ex2.qb.r \
	./tests/ex4.vb.r \
	./tests/fourway.c.r \
	./tests/hcond.c.r \
	./tests/help.c.r \
	./tests/huge1.c.r \
	./tests/huge2.c.r \
	./tests/hw.java.r \
	./tests/if2rpn.c.r \
	./tests/if2rpnq.c.r \
	./tests/if2rpntok.c.r \
	./tests/learn.ex.r \
	./tests/quadrants3.cpp.r \
	./tests/rqb2html.bas.r \
	./tests/simple.c.r \
	./tests/simple.go.r \
	./tests/skel.c.r \
	./tests/t5.cs.r \
	./tests/t6.ex.r \
	./tests/threeway.c.r \
	./tests/tryit.cpp.r \
	./tests/undo.c.r \
	./tests/version.c.r \
	./tests/babble.bbl.opt \
	./tests/bin2dec.c.opt \
	./tests/elev.c.opt \
	./tests/errors.c.opt \
	./tests/ex1.bash.opt \
	./tests/ex2.qb.opt \
	./tests/fourway.c.opt \
	./tests/help.c.opt \
	./tests/huge2.c.opt \
	./tests/hw.java.opt \
	./tests/if2rpn.c.opt \
	./tests/learn.ex.opt \
	./tests/rqb2html.bas.opt \
	./tests/simple.c.opt \
	./tests/simple.go.opt \
	./tests/skel.c.opt \
	./tests/t5.cs.opt \
	./tests/t6.ex.opt \
	./tests/threeway.c.opt \
	./tests/tryit.cpp.opt \
	./tests/undo.c.opt \
	./tests/version.c.opt \
	./tests/babble.bbl.d \
	./tests/bin2dec.c.d \
	./tests/bonus.cpp.d \
	./tests/calc.c.d \
	./tests/ccidetime.c.d \
	./tests/depeter.c.d \
	./tests/elev.c.d \
	./tests/errors.c.d \
	./tests/ex1.bash.d \
	./tests/ex2.qb.d \
	./tests/ex4.vb.d \
	./tests/fourway.c.d \
	./tests/hcond.c.d \
	./tests/help.c.d \
	./tests/huge1.c.d \
	./tests/huge2.c.d \
	./tests/hw.java.d \
	./tests/if2rpn.c.d \
	./tests/if2rpnq.c.d \
	./tests/if2rpntok.c.d \
	./tests/learn.ex.d \
	./tests/quadrants3.cpp.d \
	./tests/rqb2html.bas.d \
	./tests/simple.c.d \
	./tests/simple.go.d \
	./tests/skel.c.d \
	./tests/t5.cs.d \
	./tests/t6.ex.d \
	./tests/threeway.c.d \
	./tests/tryit.cpp.d \
	./tests/undo.c.d \
	./tests/version.c.d \
	scripts/check.sh 
