' Taken from http://www.romankoch.ch/capslock/vbdectable.htm

'CCIDE_INLINE_CODE:
'GENERATED_CODE:

'ccide-VB.m4
'Copyright (C) 2002-2004,2010,2012; Thomas W. Young, e-mail:  ccide@twyoung.com
 	' The code generated by ccide is covered by the same license as the source  
 	' code(decision table) from which it is derived. If you created the source,  
 	' you are free to do anything you like with the generated code, 
 	' including incorporating it into or linking it with proprietary software.  

DIM CCIDETABLEYES(100) As Integer
DIM CCIDETABLENO(100)  As Integer
DIM CCIDE As Integer
DIM CCIDENSTATE As Integer

              ' Return rule number 
Public Function CCIDEFINDRULE(NBRRULES As Integer, CCIDE_TABLE As Integer) As Integer
	CCIDE=0
        CCIDENSTATE=4294967295 XOR ccide_table
        WHILE  ( (CCIDETABLEYES(CCIDE) AND CCIDENSTATE) OR (CCIDETABLENO(CCIDE)  AND CCIDE_TABLE) ) AND ( CCIDE < NBRRULES )
		CCIDE = CCIDE  + 1
	WEND
	CCIDEFINDRULE=CCIDE
End Function

              ' Return rule number 
Public Function CCIDEFINDRULEYES(NBRRULES As Integer, CCIDE_TABLE As Integer) As Integer
	CCIDE=0
        CCIDENSTATE=4294967295 XOR ccide_table
        WHILE ( CCIDETABLEYES(CCIDE) AND CCIDENSTATE) AND ( CCIDE < NBRRULES )
		CCIDE = CCIDE  + 1
	WEND
	CCIDEFINDRULE=CCIDE
End Function
'END_GENERATED_CODE:

A$ = INPUT$

'DECISION_TABLE:
'   1  2  3  4 | A$ == "$$"
'  _______ | __________
'   X  -  -  - | PRINT 1
'   -  X  -  - | PRINT 2
'   -  -  X  - | PRINT 3
'   -  -  -  X | PRINT 4
'END_TABLE:
rem 
rem 
   Select Case A$  {
	CCIDE_1_"4": case "4":	rem 
	    PRINT 4
	CCIDE_1_"3": case "3":	rem 
	    PRINT 3
	CCIDE_1_"2": case "2":	rem 
	    PRINT 2
	CCIDE_1_"1": case "1":	rem 
	    PRINT 1
 END SELECT
 
rem 


