/* Skeleton Program Generated by ccide-0.6.5.1  
 
ccide is Copyright (C) 2002-2004,2010,2012;  Thomas W. Young, e-mail:  ccide@twyoung.com 
The code generated by ccide is covered by the same license as the source  
code(decision table) from which it is derived. If you created the source,  
you are free to do anything you like with the generated code, 
including incorporating it into or linking it with proprietary software.  
*/
  
#include <stdlib.h> 
#include <stdio.h> 
#include <assert.h> 
#ifdef CCIDE_LIB
#include <ccide.h>
#else 
/* CCIDE_INLINE_CODE:*/
#endif /* End #ifdef CCIDE_LIB */
static void A(int n) { 
	printf((const char*)"%i\n",n);
}
 
int main(int argc, char **argv) { 
	int C[3]={1,1,1};

	/*DECISION_TABLE:*/
	/*  Y N Y N Y N Y N | C[0] */
	/*  Y Y N N Y Y N N | C[1] */
	/*  Y Y Y Y N N N N | C[2] */
	/*  _____________________________ */
	/*  X - - - - - - - | A(0);*/
	/*  - X - - - - - - | A(1);*/
	/*  - - X - - - - - | A(2);*/
	/*  - - - X - - - - | A(3);*/
	/*  - - - - X - - - | A(4);*/
	/*  - - - - - X - - | A(5);*/
	/*  - - - - - - X - | A(6);*/
	/*  - - - - - - - X | A(7);*/
	/*END_TABLE:*/
 
	return 0; 
} 
 
/*End of Skeleton Program.*/
