// t2.cs.ccide:  Hello World in C Sharp with decision table
class Hello {
//CCIDE_INLINE_CODE:
//GENERATED_CODE:

/*
ccide-cs.m4
Copyright (C) 2010 Thomas W. Young, e-mail:  ccide@twyoung.com
This code (generated by ccide) is licensed under the GNU Library
General Public License
As such, it may be freely used, even link-editted with proprietary code
*/

int ccide_group=1;

		// Return rule number 
static int CCIDEFindRule(
	int nbrrules,  ulong ccide_table, ulong[] yes, ulong[] no){ 
        int r=0; 
        ulong nstate; 
 
        nstate = 4294967295 ^ ccide_table; 
 
        while ( 
		( ((yes[r] & nstate) >0)  ||  ( (no[r]  & ccide_table) >0) ) 
		 && ( ++r < nbrrules )  
	) {}; 
 
        return r; 
} 

static int CCIDEFindRuleYes(             // Return rule number 
	int nbrrules, ulong ccide_table, ulong[] yes)  { 
        int r=0; 
        ulong nstate;
 
        nstate = 4294967295 ^ ccide_table; 
        while ( ((yes[r] & nstate)>0)  && ( ++r < nbrrules )  ) {}; 
        return r; 
} 

static uint CCIDEb2uint(bool l) {
	if(l) return 1;
	return 0;
}

//END_GENERATED_CODE:
//GENERATED_CODE: 
// Substitution strings are: $$ and $@
//END_GENERATED_CODE: 
   
   static void Main() {
	int ccide_group=1,state=4;

        //DECISION_TABLE:					 
        //  1 2 3 |NEWGROUP		
        //  ______|________					 
        //  X - - | System.Console.WriteLine("1.");		 
        //  - X - | System.Console.WriteLine("2.Hello");	 
        //  - - X | System.Console.WriteLine("3.World");	 
        //  2 3 4 |NEWGROUP		
        //END_TABLE:						 
        //GENERATED_CODE: FOR TABLE_1.	3 Rules, 3 conditions, and 7 actions.
         { CCIDE_TABLE_1: 
		switch(ccide_group ) {
        	 case 3: CCIDE_1_3:      //Rule 3
        	    System.Console.WriteLine("3.World");
        	    ccide_group = 4;
        	    goto CCIDE_TABLE_1;
        	 case 2: CCIDE_1_2:      //Rule 2
        	    System.Console.WriteLine("2.Hello");
        	    ccide_group = 3;
        	    goto CCIDE_TABLE_1;
        	 case 1: CCIDE_1_1:      //Rule 1
        	    System.Console.WriteLine("1.");
        	    ccide_group = 2;
        	    goto CCIDE_TABLE_1;
         	        } // End Switch 
        //END_GENERATED_CODE: FOR TABLE_1, by ccide-0.2.3-2 Tue May 11 07:59:16 2010 

        //DECISION_TABLE:					 
        //  Y N Y | state==4 					 
        //  1 5 6 |NEWGROUP		
        //  ______|________					 
        //  X - - | System.Console.WriteLine("4.");		 
        //  - X - | System.Console.WriteLine("5.Goodbye");	 
        //  - - X | System.Console.WriteLine("6.World");	 
        //  5 4 - | state=$$;					 
        //  5 6 7 |NEWGROUP		
        //END_TABLE:						 
        //GENERATED_CODE: FOR TABLE_2.	3 Rules, 4 conditions, and 9 actions.
         {	ulong[] CCIDE_table2_yes={9UL, 4UL, 3UL};
        ulong[] CCIDE_table2_no={0UL, 1UL, 0UL};
        	ccide_group=1;

        CCIDE_TABLE_2:
        	switch(CCIDEFindRule(3,
        		  (state==4)
        		| (ccide_group == 1)<<1
        		| (ccide_group == 5)<<2
        		| (ccide_group == 6)<<3
        		  ,CCIDE_table2_yes, CCIDE_table2_no)) {
        	 case 0: CCIDE_2_0:      //Rule 3
        	    System.Console.WriteLine("6.World");
        	    ccide_group = 7;
        	    goto CCIDE_TABLE_2;
        	 case 1: CCIDE_2_1:      //Rule 2
        	    System.Console.WriteLine("5.Goodbye");
        	    state=4;
        	    ccide_group = 6;
        	    goto CCIDE_TABLE_2;
        	 case 2: CCIDE_2_2:      //Rule 1
        	    System.Console.WriteLine("4.");
        	    state=5;
        	    ccide_group = 5;
        	    goto CCIDE_TABLE_2;
        		        } // End Switch
        //END_GENERATED_CODE: FOR TABLE_2, by ccide-0.2.3-2 Tue May 11 07:59:16 2010 
	
	if(ccide_group == 7) System.Console.WriteLine("Success!\n");
	else System.Console.WriteLine("Failed.\n");
 
    };  // End of Main

}; 
