    ccidew version 0.6.5-1, Copyright (C) 2002-2004,2010,2012 Thomas W. Young, e-mail ccide@twyoung.com
    ccide comes with ABSOLUTELY NO WARRANTY.    ccide is Copyright (C) 2002-2004,2010,2012;  Thomas W. Young, e-mail:  ccide@twyoung.com 
    ccide is free software, and you are welcome to redistribute it 
    under certain conditions; see file COPYING for details. 
 
The code generated by ccide is covered by the same license as the source  
code(decision table) from which it is derived. If you created the source,  
you are free to do anything you like with the generated code, 
including incorporating it into or linking it with proprietary software.  
